name: weather_app
description: Application météo avec intégration OpenWeatherMap
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  # google_maps_flutter: ^2.5.0

  # HTTP Client
  http: ^1.2.0
  dio: ^5.4.0

  # Retrofit (client API type-safe)
  retrofit: ^4.9.2

  # Sérialisation JSON
  json_annotation: ^4.9.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Générateurs de code
  build_runner: ^2.11.1
  retrofit_generator: ^10.2.3
  json_serializable: ^6.8.0

  flutter_lints: ^3.0.1
